version: '1.0'

services:
  database:
    image: tlt-database:latest
    build: src/database/
    hostname: database
    ports:
      - "8888:8888"
  server:
    image: tlt-server:latest
    build: src/server/
    hostname: server
    depends_on:
      - database
    ports:
      - "6666:6666"
  client-1:
    image: tlt-client-1:latest
    build: src/client/
    hostname: client1
    entrypoint: /client.py
    depends_on:
     - server
  client-2:
    image: tlt-client-2:latest
    build: src/client/
    hostname: client2
    depends_on:
      - server
